sudo: required
services:
  - docker

before_install:
  - docker build -t jeffhogg86/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeffhogg86/react-test npm test -- --coverage

after_success:
  - docker build -t jeffhogg86/multi-client ./client
  - docker build -t jeffhogg86/multi-nginx ./nginx
  - docker build -t jeffhogg86/multi-server ./server
  - docker build -t jeffhogg86/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jeffhogg86/multi-client
  - docker push jeffhogg86/multi-nginx
  - docker push jeffhogg86/multi-server
  - docker push jeffhogg86/multi-worker
